Choose Your Own Adventure Player
stashapp/CommunityScripts pull request #424
Opened 2024-09-02 20:38 UTC by cj12312021

This is a WIP PR for the Choose Your Own Adventure Player plugin. For now, this PR mostly just contains some documentation as well as a sample game I put together to demo the features as well as illustrate how things work.

2025-01-27 04:07 UTC, DogmaDragon requested changes

2025-01-27 04:07 UTC, DogmaDragon commented on plugins/chooseYourAdventurePlayer/chooseYourAdventurePlayer.yml
> +    - cyap-min.js
Is  `cyap.min.js` not included in the source or linked externally on purpose?

2025-01-27 04:07 UTC, DogmaDragon commented on plugins/chooseYourAdventurePlayer/chooseYourAdventurePlayer.yml
> +    - chooseYourAdventurePlayer.css
Missing source file.

2025-01-27 14:14 UTC, stg-annon commented on plugins/chooseYourAdventurePlayer/chooseYourAdventurePlayer.yml
> +    - cyap-min.js
my understanding is that they want to limit the plugin to backers but advertise the plugins existence in this repo, the missing files are provided via a private repo

2025-01-30 01:16 UTC, cj12312021 commented on plugins/chooseYourAdventurePlayer/chooseYourAdventurePlayer.yml
> +    - chooseYourAdventurePlayer.css
See my post here: https://discordapp.com/channels/559159668438728723/742220889017417738/1333190984070205460. I intend to keep the JS file behind a private repo meant for members only. I want to keep the plugin on the script page with instructions on attaining pull access to make maker backer benefits visible.

2025-01-30 01:17 UTC, cj12312021 commented on plugins/chooseYourAdventurePlayer/chooseYourAdventurePlayer.yml
> +    - chooseYourAdventurePlayer.css
Please hold off on merging this PR as I sort some details out with [stg-annon](https://github.com/stg-annon). The instruction here will need another pass.

2025-01-30 06:14 UTC, DogmaDragon commented on plugins/chooseYourAdventurePlayer/chooseYourAdventurePlayer.yml
> +    - chooseYourAdventurePlayer.css
That was my understanding with .js file, but does the same is true for the missing .css file? GitHub didn't allow me to highlight a single line.

2025-01-31 02:02 UTC, cj12312021 commented on plugins/chooseYourAdventurePlayer/chooseYourAdventurePlayer.yml
> +    - chooseYourAdventurePlayer.css
Yeah, I considered including the CSS file, but I ultimately decided against it because providing it would not be of any real benefit.

I just pushed more changes to the branch. I think it's in a good state for an initial release.

2025-02-01 09:29 UTC, merged